import chalk from "chalk";

import type { Color } from "../domain/game/move.ts";

import {
  GRID_MAX_HEIGHT,
  type Game,
  type PieceCount,
} from "../domain/game/game.ts";
import { getPieceShapeFromMove } from "../domain/game/piece-shape-from-move.ts";
import { getNodeTag } from "../domain/state/detect-victory.ts";

const PIECE_MAX_HEIGHT = 3;

export function displayGame(game: Game) {
  let rows = getGridAsStrings(game);
  rows = addRemainingPiecesToRows(rows, game.availablePieces);

  console.clear();
  rows.forEach((row) => console.log(row));

  if (game.victory) {
    const color =
      game.turnOfPlayer === "blue"
        ? chalk.blueBright(game.turnOfPlayer)
        : chalk.white(game.turnOfPlayer);
    console.log(`Victory of the player ${color} ! Congratulations !`);
  }
}

/**
 * Get an array of 9 strings (of length 9) that, once printed, display the current game grid.
 */
export function getGridAsStrings(game: Game): Array<string> {
  const rows: Array<string> = [];

  game.grid.forEach((column: Array<string>, x) => {
    column.forEach((cell, y) => {
      const relevantRow = GRID_MAX_HEIGHT - y;
      if (!rows[relevantRow]) {
        rows[relevantRow] = "";
      }
      if (game.victory && game.victory.includes(getNodeTag(x, y))) {
        rows[relevantRow] += stringCellToChalkDisplay(cellToVictoryCell(cell));
      } else {
        rows[relevantRow] += stringCellToChalkDisplay(cell);
      }
    });
  });

  return rows.map((r) => r + " ");
}

/**
 * Concat, to an array generated by getGridAsStrings,
 * the text allowing to display the remaining pieces that have not yet been played.
 */
function addRemainingPiecesToRows(
  rows: Array<string>,
  availablePieces: Array<PieceCount>,
): Array<string> {
  const updatedRows = [
    ...rows,
    "1 2 3 4 5 6 7 8 9  ",
    "                   ",
    "                   ",
    "                   ",
  ];

  const remainingBluePieces = availablePieces.filter((p) => p.color === "blue");
  const remainingWhitePieces = availablePieces.filter(
    (p) => p.color === "white",
  );
  const blueTotal = remainingBluePieces
    .map((p) => p.count)
    .reduce((accumulator, value) => {
      return accumulator + value;
    }, 0);
  const whiteTotal = remainingWhitePieces
    .map((p) => p.count)
    .reduce((accumulator, value) => {
      return accumulator + value;
    }, 0);

  const bluePiecesStrings = generateAvailablePiecesStrings(
    "blue",
    remainingBluePieces,
  );
  const whitePiecesStrings = generateAvailablePiecesStrings(
    "white",
    remainingWhitePieces,
  );

  updatedRows[0] += `   ${chalk.blueBright("BLUE")} stock:  ${blueTotal} pieces`;
  updatedRows[1] += `    1       2       3I      3L      4S      4T      4L`;
  bluePiecesStrings.forEach((str, index) => {
    updatedRows[2 + index] += str;
  });

  updatedRows[6] += chalk.underlineWhiteBright(
    "                                           ",
  );

  updatedRows[7] += `   ${chalk.white("WHITE")} stock:  ${whiteTotal} pieces`;
  updatedRows[8] += `    1       2       3I      3L      4S      4T      4L`;
  whitePiecesStrings.forEach((str, index) => {
    updatedRows[9 + index] += str;
  });

  return updatedRows;
}

function generateAvailablePiecesStrings(
  color: Color,
  availablePieces: Array<PieceCount>,
): Array<string> {
  const generatedStrings = ["  ", "  ", "  ", "  "];
  availablePieces.forEach((pieceCount) => {
    const pieceShape = getPieceShapeFromMove({
      color,
      skipped: false,
      piece: pieceCount.piece,
      rotation: 0,
    });

    // Cannot use foreach because some pieces are smaller than the display
    for (let x = 0; x < PIECE_MAX_HEIGHT; x++) {
      for (let y = 0; y < PIECE_MAX_HEIGHT; y++) {
        const cellValue = pieceShape[x]?.at(y) ?? 0;
        const affectedRow = PIECE_MAX_HEIGHT - 1 - y;
        generatedStrings[affectedRow] += intCellToChalkDisplay(
          cellValue,
          color,
        );
      }
    }

    if (pieceCount.count === 2) {
      generatedStrings[3] +=
        color === "blue" ? chalk.blueBright("  ◉◉  ") : chalk.white("  ◉◉  ");
    } else if (pieceCount.count === 1) {
      generatedStrings[3] +=
        color === "blue" ? chalk.blueBright("  ◉○  ") : chalk.white("  ◉○  ");
    } else {
      generatedStrings[3] +=
        color === "blue" ? chalk.blueBright("  ○○  ") : chalk.white("  ○○  ");
    }

    generatedStrings.forEach(
      (_str, index) => (generatedStrings[index] += "  "),
    );
  });

  return generatedStrings;
}

function stringCellToChalkDisplay(cell: string): string {
  switch (cell) {
    case "w":
      return chalk.bgWhite("  ");
    case "b":
      return chalk.bgBlueBright("  ");
    case "W":
      return chalk.bgWhite.black("◀▶");
    case "B":
      return chalk.bgBlueBright.black("◀▶");
    case "V": // Blue victory
      return chalk.bgBlueBright.black("◖◗");
    case "L": // White victory
      return chalk.bgWhite.black("◖◗");
    case ".":
    default:
      return chalk.grey("⚬ ");
  }
}

function cellToVictoryCell(cell: string): string {
  if (/w/i.test(cell)) {
    return "L";
  } else {
    return "V";
  }
}

function intCellToChalkDisplay(cell: number, color: Color): string {
  if (color === "blue" && cell === 1) {
    return chalk.bgBlueBright("  ");
  } else if (color === "white" && cell === 1) {
    return chalk.bgWhite("  ");
  }
  return chalk.grey("⚬ ");
}
